faceblog/models.py
from faceblog import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    profile_image = db.Column(db.String(20), nullable=False, default='default_profile.png')
    email = db.Column(db.String(db.String(64)), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    posts = db.relationship('BlogPost', backref="author", lazy= True)

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password = password

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"Username {self.username}"


class BlogPost(db.Model):
    users = db.relationship(User)

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    title = db.Column(db.String(140), nullable=False)
    text = db.Column(db.Text, nullable=False)

    def __init__(self, title, text, user_id):
        self.title = title
        self.text = text
        self.user_id = user_id

    def __repr__(self):
        return f"Post ID: {self.id} -- Date: {self.date} --- {self.title}"

faceblog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import  FileField, FileAllowed

from flask_login import current_user
from faceblog.models import User

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log in')

class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message="Password must match")])
    password_confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register!')

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')
    
    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!')


class UpdateUserForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),Email()])
    username = StringField('Username', validators=[DataRequired()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')
    
    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!')

faceblog/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecret'

####DATABASE
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

####Login
login_manager = LoginManager()

login_manager.init_app(app)
login_manager.login_view = 'users.login'


from faceblog.core.views import core
from faceblog.error_pages.handlers import error_pages
from faceblog.users.views import users

app.register_blueprint(core)
app.register_blueprint(error_pages)
app.register_blueprint(users)

faceblog/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

faceblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from faceblog import db
from faceblog.models import User, BlogPost
from faceblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from faceblog.users.pic_handler import add_profile_pic

users = Blueprint('users', __name__)

@users.route('/register', methods =['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email = form.email.data,
                    username=form.username.data, 
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form = form)

@users.route('/login', methods =['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Log in Sucess!")

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')
            
            return redirect(next)

    return render_template('login.html', form=form)



@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username = username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

faceblog/templates/account.html
{% extends 'base.html' %} {% block head %}
<title>Account</title>
{% endblock %} {% block body %}
<h2>Account </h2>
<div>
    <h1>Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{url_for('static', filename='profile_pics/'+current_user.profile_image)}}">
</div>
<div class="container">
    <form method="POST">
        {{form.hidden_tag()}}
        <br> {{form.username.label}}{{form.username}}
        <br> {{form.email.label}}{{form.email}}
        <br> {{form.picture.label}}{{form.picture}}
        <br> {{form.submit()}}
    </form>

</div>
<hr> {% endblock %}

faceblog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {% block head %} {% endblock %}
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">WebSiteName</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{{url_for('core.index')}}">Home</a></li>
                <li><a href="{{url_for('core.info')}}">About</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('users.logout')}}">Log out</a></li>
                <li><a href="{{url_for('users.account')}}">Account</a></li>
                <li><a href="{{url_for('core.info')}}">Create Post</a></li>
                {% else %}
                <li><a href="{{url_for('users.login')}}">Log in</a></li>
                <li><a href="{{url_for('users.register')}}">Register</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body %} {% endblock %}
    </div>
</body>

</html>

faceblog/templates/edit.html
{% extends 'base.html' %} {% block head %}
<title>Edit Post</title>
{% endblock %} {% block body %}
<h2>Edit Blog Post: </h2>
<form action="/posts/edit/{{post.id}}" method="POST">
    {{form.hidden_tag()}} Title: <input type="text" name='title' id="title" value="{{post.title}}">
    <br> Post: <input type="text" name="content" id="content" value="{{post.content}}">
    <br>
    <input type="submit" value='Post'>
</form>
<hr> {% endblock %}

faceblog/templates/index.html
{% extends 'base.html' %}

{% block head %}
<title>Posts</title>
{% endblock %}

{% block body %}
<h1>Home Page</h1>
{% endblock %}

faceblog/templates/info.html
{% extends 'base.html' %} {% block head %}
<title>About us</title>
{% endblock %} {% block body %}
<h2>About us: </h2>
<h3>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium distinctio necessitatibus vitae deserunt ullam hic, provident doloribus molestias placeat asperiores fugiat sunt officiis at! Vitae doloribus aspernatur quisquam nesciunt ea.</h3>
{% endblock %}

faceblog/templates/login.html
{% extends 'base.html' %} {% block head %}
<title>Login</title>
{% endblock %} {% block body %}
<h2>Login </h2>
<form method="POST">
    {{form.hidden_tag()}} {{form.email.label()}} {{form.email}}

    <br> {{form.password.label()}} {{form.password}}

    <br> {{form.submit()}}
</form>
<hr> {% endblock %}

faceblog/templates/posts.html
{% extends 'base.html' %}

{% block head %}
<title>Posts</title>
{% endblock %}

{% block body %}
<h1>All Posts</h1>
<hr>
<h2>Create New Blog Post: </h2>


<form action="/posts" method="POST">
    Title: <input type="text" name='title' id="title">
    <br>
    Post: <input type="text" name="content" id="content">
    <br>
    <input type="submit" value='Post'>
</form>
<hr>
{% for post in posts %}
<h2>{{post.title}}</h2>

{% if post.author %}
<h3>By: {{ post.author }}</h3>
{% else %}
<h3>By: N/A</h3>
{% endif %}

<p>{{post.content}}</p>
<a href="/posts/delete/{{post.id}}">Delete</a>
<a href="/posts/edit/{{post.id}}">Edit</a>
<hr>
{% endfor %}
{% endblock %}

faceblog/templates/register.html
{% extends 'base.html' %} {% block head %}
<title>Registration</title>
{% endblock %} {% block body %}
<h2>Edit Blog Post: </h2>
<form action="/posts/edit/{{post.id}}" method="POST">
    {{form.hidden_tag()}} Title: <input type="text" name='title' id="title" value="{{post.title}}">
    <br> Post: <input type="text" name="content" id="content" value="{{post.content}}">
    <br>
    <input type="submit" value='Post'>
</form>
<hr> {% endblock %}

faceblog/templates/user_blog_posts.html
{% extends 'base.html' %} {% block head %}
<title>Post</title>
{% endblock %} {% block body %}
<h2>Blog Posts: </h2>
<div>
    <div>
        <h1>Welcome to the page for {{user.username}}</h1>
        <img src="{{url_for('static', filename = 'profile_pics/'+user.profile_image)}}" alt="">
    </div>
</div>

{% for post in blog_posts.items %}
<h2>
    <a href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a></h2>
Written By: <a href="{{url_for('users.user_post', username=post.author.username)}}">{{post.author.username}}</a>
<p>Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
<br>
<p>{{post.text}}</p>
<br> {% endfor %}

<nav aria-label="Page Navigation Example">
    <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current = 1, right_current=2) %} {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" hr ef="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
        </li> {% endif %} {% endfor %}
    </ul>
</nav>


{% endblock %}